name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 141.145.207.219
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Proceed with deployment
            cd ~/GitProjects/QuiSON
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            sudo mkdir -p /var/www/quison
            sudo rm -fr /var/www/quison/*
            sudo cp -R ./dist/quison/browser/* /var/www/quison
